---
- name: Disable swap
  shell: swapoff --all

- name: Install epel-release
  yum:
    name: epel-release-7
    state: present

- name: Install htop
  yum:
    name: htop-{{ htop_version }}
    state: present
...
