---
- name: Install common packages and configuration
  hosts: all
  roles:
    - common
    - firewalld
    - docker

- name: Kubernetes hosts
  hosts: kubernetes
  roles:
    - masternode
    - workernode

- name: Hosts that control kubernetes
  hosts: clustercontrol
  roles:
    - clustercontrol
    - rke
...
