---
- name: Install RKE
  get_url:
    url: https://github.com/rancher/rke/releases/download/{{ rke_cli }}/rke_linux-amd64
    dest: /usr/bin/rke
    checksum: sha256:{{ rke_cli_sha256 }}
    mode: 0755
...
